[package]
name = "mpeg-parser"
version = "0.1.0"
authors = ["Simi Falaye <simifalaye1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
